#!/bin/sh -xe

clean_up() {
    rm -rf GM2Calc
    rm -rf build
}

trap clean_up 0
trap "exit 1" INT QUIT TERM

clean_up

source=${SOURCE:-"https://github.com/GM2Calc/GM2Calc"}

git clone "$source" GM2Calc

( cd GM2Calc && \
  mkdir build && \
  cd build && \
  cmake -DCMAKE_INSTALL_PREFIX=local .. && \
  make -j4 && \
  make install )

export LD_LIBRARY_PATH="$PWD/GM2Calc/build/local/lib:${LD_LIBRARY_PATH}"
export PKG_CONFIG_PATH="GM2Calc/build/local/lib/pkgconfig"

( meson build && \
  cd build && \
  ninja && \
  ./example && \
  ./example-c )
